### PR TITLE
Added Skyline.java

### PR DESCRIPTION
**Pull request by DolphinWorld**
This is for leetcode problem listed in DivideAndConquer. 

https://leetcode.com/problems/the-skyline-problem/

---

This change is [Reviewable](https://reviewable.io/reviews/codersinseattle/interviewproblems/15)

### CODE REVIEW

**Comment by yukuairoy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[Problems/src/DivideAndConquer/Skyline.java, line 44 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15#-KQUKGtmYglVK3kwTP8T:-KQUKGtmYglVK3kwTP8U:bn3h0mu) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/9a2db9e3b89dea455f0dac2f35485232f88b182b/Problems/src/DivideAndConquer/Skyline.java#L44)):_

> ``` Java
>     class HeightComparator implements Comparator<int[]> {
>         @Override 
>         public int compare(int[] a, int[] b) {
> ```

The logic can be simplified to: return b[2] - a[2]

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15)_

**Comment by yukuairoy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[Problems/src/DivideAndConquer/Skyline.java, line 31 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15#-KQUKfe8e2XIR3sTLQ8_:-KQUKfe9JFCQTSuacq6X:b9qddhh) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/9a2db9e3b89dea455f0dac2f35485232f88b182b/Problems/src/DivideAndConquer/Skyline.java#L31)):_

> ``` Java
>         return ans;
>     }
>     private Map<Integer, List<int[]>> flattern(int buildings[][]) {
> ```

I think you meant "flatten" instead of "flattern".

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15)_

**Comment by DolphinWorld** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[Problems/src/DivideAndConquer/Skyline.java, line 31 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15#-KQUKfe8e2XIR3sTLQ8_:-KQWD8C3iCNAqIhPiYv-:b-js2fcc) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/9a2db9e3b89dea455f0dac2f35485232f88b182b/Problems/src/DivideAndConquer/Skyline.java#L31)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> I think you meant "flatten" instead of "flattern".
> </details>
> Yes, I will fix

---

_[Problems/src/DivideAndConquer/Skyline.java, line 44 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15#-KQUKGtmYglVK3kwTP8T:-KQWDVasiJisQyXFulLU:birnhjo) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/9a2db9e3b89dea455f0dac2f35485232f88b182b/Problems/src/DivideAndConquer/Skyline.java#L44)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> The logic can be simplified to: return b[2] - a[2]
> </details>
> There will be overflow problem, eg b[2] == -2147483648 a[2] == 2147483647,  we expect to see b[2] - a[2] to be negative number, but actually it returns 1 in Java, since Java using 32 bit Integer.  Leetcode has this kind of testing case, so I changed to this way

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/15)_

**Comment by DolphinWorld** [comment]
Checked in.

**Pull request closed without merging**
