### PR TITLE
Style-check all Python modules in the repository.

### PR DESCRIPTION
**Pull request by yukuairoy**
This change is [Reviewable](https://reviewable.io/reviews/codersinseattle/interviewproblems/6)

### CODE REVIEW

**Comment by stonemary** [comment]
Build failed for py3, are you able to view --> https://travis-ci.org/CodersInSeattle/InterviewProblems/builds/155690766 ?
Please fix the compatibility issue before merge. (style failing is fine). 

---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[check_style.py, line 5 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFIUhttOq6blcuiKdk:-KQFIUhttOq6blcuiKdl:b-sd8g82) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L5)):_

> import logging
> import re
> import os
> import subprocess
> import sys

this is of course a  nitpick. But usually we rank them alphabetically (you can use IntelliJ/PyCharm's `optimize import` function i think)

---

_[check_style.py, line 9 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFJ6nsSwWOrwgXTkAf:-KQFJ6nttmUjE4jGdnsg:by062pc) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L9)):_

> ``` Python
> 
> logging.basicConfig(level=logging.INFO)
> LOGGER = logging.getLogger(__name__)
> ```

Interesting. I typically only use CAPITAL for constants and i thought that's the convention, am I mistaken? 

---

_[check_style.py, line 21 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFJr4rq7eRKzYCp-VG:-KQFJr4rq7eRKzYCp-VH:b5lak8a) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L21)):_

> ``` Python
> 
>     def check_style(self, module):
>         '''Runs pylint on a Python module.'''
> ```

I don't like this one too much either, but for your interests, I should mention that there is indeed a PEP saying that docstrings should be """ triple double quotes """ 
https://www.python.org/dev/peps/pep-0257/
Same thing with all the other docstrings. 

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQFL6zH3IZ84-asZUU-:bn17ikm) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_

> ``` Python
>         try:
>             subprocess.check_output(['pylint', module])
>             LOGGER.debug('%s PASSED.', module)
> ```

if you are concerned about compatibility with <= py2.5, use `%`; otherwise use `.format`: the former is obsolete. 

---

_[check_style.py, line 30 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFM0buvahYx-5ATbB6:-KQFM0buvahYx-5ATbB7:b-od4lcp) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L30)):_

> score = re.search(r'[-0-9]+.\d{2}/10',
>                                   linter_message).group(0)

two things:
1. in py3 `linter_message` seems to be a byte-like object, which probly need to be encode/decoded before passing into re.search; this is what broke the build;
2. just FYI. there is a way to make regex more readable: https://docs.python.org/3/library/re.html#re.VERBOSE

---

_[check_style.py, line 34 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFMh-z0sBywlnWx4Im:-KQFMh0-6c6We2Qq51bP:b6z4s6r) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L34)):_

> ``` Python
>                                os.path.relpath(module), score)
>                 self.failed += 1
>             except AttributeError:
> ```

I understand the code here is trying to catch `None.group(0)`; however I do not recommend this approach - 
1. this does not seem to be a good use case for exceptions when line 28 could just check for `None` - which will make the code much more explicit and clear. 
2. if exception was used, the try clause is still too wide. 

---

_[check_style.py, line 55 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFOqAmqq-YpOZIXFrP:-KQFOqAmqq-YpOZIXFrQ:b-bluo3b) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L55)):_

> class Pep8Runner(object):
>  
>     def **init**(self):
>         self.passed = 0
>         self.failed = 0
>  
> <details><summary>
> 
> <i alt="summary">Quoted 12 lines of code…</i></summary>
> 
> 
>     def check_style(self, module):
>         '''Runs pep8 on a Python module.'''
>         try:
>             subprocess.check_output(['pep8', module])
>             LOGGER.debug('%s PASSED.', module)
>             self.passed += 1
>         except subprocess.CalledProcessError as pep8_error:
>             pep8_message = pep8_error.output
>             LOGGER.warning('%s FAILED PEP8', os.path.relpath(module))
>             self.failed += 1
>             for pep8_warning in pep8_message.splitlines():
>                 LOGGER.warning(pep8_warning)
> </details>

=) If this were a work CR, I would say those two classes look too similar. Might be worthy it to write a `CommonRunner` and use the power of inheritance. It will be much better to maintain later if you are going to have more `Runner`s. But I think this is fine for our code base for now. 

---

_[check_style.py, line 76 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFQczBfLY4RffxIT-M:-KQFQczBfLY4RffxIT-N:b-21vkye) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L76)):_

> pylint_runner = PylintRunner()
> pep8_runner = Pep8Runner()

I recommend store those objects (with their names) in a dictionary or list, and use for loops later in `if _should_check...` and `LOGGER.info`. This way you can add more `runners` easier later. 

---

_[check_style.py, line 99 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFRTA_TYZi5cVV5RcT:-KQFRTAalTVKScpr4bmr:bf9bdco) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L99)):_

> ``` Python
> 
> if __name__ == '__main__':
>     main()
> ```

since we CR to learn, I would like to mention that there is a wonderful library called `click` for python script argument parsing. I should probably donate to its author for the troubles it saved me. I do recall some python3 limitations though.. 

---

_[requirements.txt, line 4 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFSw6pcZs19FT2srfr:-KQFSw6pcZs19FT2srfs:bomuwb2) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/requirements.txt#L4)):_

> pep8
> pylint

lock versions. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-:-KQFH5zdIoIlnEg7JQSz:b-t5g0ok)_

**Comment by stonemary** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by JesseZhuang** [comment]
I tested running `python check_style.py` from the command line and got following errors:

``` bash
INFO:__main__:Checking E:\projects\seattle-leetcoders\InterviewProblems\check_style.py
Traceback (most recent call last):
  File "check_style.py", line 23, in check_style
    subprocess.check_output(['pylint', module])
  File "C:\Users\zhzex\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\zhzex\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pylint', 'E:\\projects\\seattle-leetcoders\\InterviewProblems\\check_style.py']' returned non-zero exit status 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_style.py", line 99, in <module>
    main()
  File "check_style.py", line 83, in main
    pylint_runner.check_style(file_path)
  File "check_style.py", line 30, in check_style
    linter_message).group(0)
  File "C:\Users\zhzex\AppData\Local\Programs\Python\Python35-32\lib\re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

Used a virtualenv with following packages installed:

``` bash
>pip list
astroid (1.4.8)
colorama (0.3.7)
isort (4.2.5)
lazy-object-proxy (1.2.2)
mccabe (0.5.2)
pep8 (1.7.0)
pip (8.1.1)
py (1.4.31)
pylint (1.6.4)
pytest (3.0.1)
setuptools (20.10.1)
six (1.10.0)
wrapt (1.10.8)
```

**Comment by stonemary** [comment]
sorry, i was using reviewable for the CR. it doesnt seem to be working so well. I will switch to github comments.

**Comment by yukuairoy** [comment]
Review status: 3 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[check_style.py, line 5 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFIUhttOq6blcuiKdk:-KQJHCuFFtU0HNdcaKS9:b-896fix) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L5)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> > import logging
> > import re
> > import os
> > import subprocess
> > import sys
> 
> this is of course a  nitpick. But usually we rank them alphabetically (you can use IntelliJ/PyCharm's `optimize import` function i think)
> </details>
> Done.

---

_[check_style.py, line 9 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFJ6nsSwWOrwgXTkAf:-KQJHpiTGyrRcqKW9Clx:b2u15ar) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L9)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> Interesting. I typically only use CAPITAL for constants and i thought that's the convention, am I mistaken? 
> </details>
> I prefer global instance to also be capitalized. Couldn't find any references though.

---

_[check_style.py, line 21 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFJr4rq7eRKzYCp-VG:-KQJI_nhKWviauBW4dpC:b-896fix) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L21)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> I don't like this one too much either, but for your interests, I should mention that there is indeed a PEP saying that docstrings should be """ triple double quotes """ 
> https://www.python.org/dev/peps/pep-0257/
> Same thing with all the other docstrings. 
> </details>
> Done.

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQJJBnbg7UqndvFxeg3:b-6m3lqy) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> if you are concerned about compatibility with <= py2.5, use `%`; otherwise use `.format`: the former is obsolete. 
> </details>
> I find %s way more intuitive to use than .format partially because this is the way format string is done in many other languages. I disagree that the former is obsolete-it's widely used as far as I can tell, especially for logging:
> See this for example: https://docs.python.org/2/library/logging.html#logging.Logger.debug

---

_[check_style.py, line 30 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFM0buvahYx-5ATbB6:-KQJJqU4rld0xXMaCsXN:br0wcbn) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L30)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> > score = re.search(r'[-0-9]+.\d{2}/10',
> >                                   linter_message).group(0)
> 
> two things:
> 1. in py3 `linter_message` seems to be a byte-like object, which probly need to be encode/decoded before passing into re.search; this is what broke the build;
> 2. just FYI. there is a way to make regex more readable: https://docs.python.org/3/library/re.html#re.VERBOSE
> 
> </details>
> re.VERBOSE is cool but in this case the regex seems simple enough to decipher.

---

_[check_style.py, line 34 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFMh-z0sBywlnWx4Im:-KQJKRqB7q6_nVbNARHc:b-9fmn3c) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L34)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> I understand the code here is trying to catch `None.group(0)`; however I do not recommend this approach - 
> 1. this does not seem to be a good use case for exceptions when line 28 could just check for `None` - which will make the code much more explicit and clear. 
> 2. if exception was used, the try clause is still too wide. 
> </details>
> Good suggestion. Done.

---

_[check_style.py, line 55 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFOqAmqq-YpOZIXFrP:-KQJKmaKLhyskvl1Yxul:b-uo4igz) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L55)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> > class Pep8Runner(object):
> >  
> >     def **init**(self):
> >         self.passed = 0
> >         self.failed = 0
> >  
> >     def check_style(self, module):
> >         '''Runs pep8 on a Python module.'''
> >         try:
> >             subprocess.check_output(['pep8', module])
> >             LOGGER.debug('%s PASSED.', module)
> >             self.passed += 1
> >         except subprocess.CalledProcessError as pep8_error:
> >             pep8_message = pep8_error.output
> >             LOGGER.warning('%s FAILED PEP8', os.path.relpath(module))
> >             self.failed += 1
> >             for pep8_warning in pep8_message.splitlines():
> >                 LOGGER.warning(pep8_warning)
> 
> =) If this were a work CR, I would say those two classes look too similar. Might be worthy it to write a `CommonRunner` and use the power of inheritance. It will be much better to maintain later if you are going to have more `Runner`s. But I think this is fine for our code base for now. 
> </details>
> This will be a TODO.

---

_[check_style.py, line 76 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFQczBfLY4RffxIT-M:-KQJKc_Jmn_IrGosA-Yi:b-uo4igz) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L76)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> > pylint_runner = PylintRunner()
> > pep8_runner = Pep8Runner()
> 
> I recommend store those objects (with their names) in a dictionary or list, and use for loops later in `if _should_check...` and `LOGGER.info`. This way you can add more `runners` easier later. 
> </details>
> This will be a TODO.

---

_[check_style.py, line 99 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFRTA_TYZi5cVV5RcT:-KQJKZqBZMsN0QToK2GS:bwasc61) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L99)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> since we CR to learn, I would like to mention that there is a wonderful library called `click` for python script argument parsing. I should probably donate to its author for the troubles it saved me. I do recall some python3 limitations though.. 
> </details>
> argparsing will be a TODO.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by yukuairoy** [comment]
Review status: 2 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[requirements.txt, line 4 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFSw6pcZs19FT2srfr:-KQK5MGWk1rh-3bXuFpj:b-896fix) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/requirements.txt#L4)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> > pep8
> > pylint
> 
> lock versions. 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by stonemary** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQK6bZSep4Z5RfXtABp:b-olulp0) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> I find %s way more intuitive to use than .format partially because this is the way format string is done in many other languages. I disagree that the former is obsolete-it's widely used as far as I can tell, especially for logging:
> See this for example: https://docs.python.org/2/library/logging.html#logging.Logger.debug
> </details>
> I used the wrong word `obsolete`. But one shall use .format for new code - see this stackoverflow answer, it contains links from python offical docs. - http://stackoverflow.com/questions/13451989/pythons-many-ways-of-string-formatting-are-the-older-ones-going-to-be-deprec

---

_[python_style_checker.py, line 33 [r2]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQK8tsAf_zE2dBpNLWS:-KQK8tsAf_zE2dBpNLWT:b-568zop) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/8c7f94669035f6d378e0d4929b1aa96aab3e5827/python_style_checker.py#L33)):_

> ``` Python
>         '''Runs pylint on a Python module.'''
>         try:
>             subprocess.check_output(['pylint', module])
> ```

`subprocess.check_output([self.linter_name, module])`
if `self.linter_name` is the process name. otherwise it can be another class attribute --- just don't use a magic string directly. Same with the PEP8Runner. 

---

_[python_style_checker.py, line 38 [r2]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQK9fAi9LR9O8-awAVA:-KQK9fAi9LR9O8-awAVB:b9rxbkn) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/8c7f94669035f6d378e0d4929b1aa96aab3e5827/python_style_checker.py#L38)):_

> ``` Python
>         except subprocess.CalledProcessError as pylint_error:
>             linter_message = pylint_error.output
>             score_found = re.search(br'[-0-9]+\.\d{2}/10', linter_message)
> ```

you still need to check if `score_found` is None or not, as well as possibly decode/encode `linter_message` for python3 compatibility =)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by stonemary** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by yukuairoy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQKBJhD5iQTX3jTpk5x:b-fcxvls) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> I used the wrong word `obsolete`. But one shall use .format for new code - see this stackoverflow answer, it contains links from python offical docs. - http://stackoverflow.com/questions/13451989/pythons-many-ways-of-string-formatting-are-the-older-ones-going-to-be-deprec
> </details>
> I concur jsbueno's answer in your stackoverflow link:
> "Every time the subject is raised on Python development list, there is strong controversy on which is better, but no controversy on whether to remove the classic way - it will stay. Despite being denoted on PEP 3101, Python 3.1 had come and gone, and % formatting is still around.

The statements for the keeping classic style are clear: it is simple, it is fast, it is quick to do for short things."

---

_[python_style_checker.py, line 33 [r2]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQK8tsAf_zE2dBpNLWS:-KQKCKYpznwBr3HTMs_z:b-9fmn3c) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/8c7f94669035f6d378e0d4929b1aa96aab3e5827/python_style_checker.py#L33)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> `subprocess.check_output([self.linter_name, module])`
> if `self.linter_name` is the process name. otherwise it can be another class attribute --- just don't use a magic string directly. Same with the PEP8Runner. 
> </details>
> Good suggestion. Done.

---

_[python_style_checker.py, line 38 [r2]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQK9fAi9LR9O8-awAVA:-KQKCP_v07AeXpKrfVGU:bj37od6) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/8c7f94669035f6d378e0d4929b1aa96aab3e5827/python_style_checker.py#L38)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> you still need to check if `score_found` is None or not, as well as possibly decode/encode `linter_message` for python3 compatibility =)
> </details>
> I haven't seen a case where score_found is None so I'll leave it like this for now. Will patch it if it problems arise.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by stonemary** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQKIHzI9W25cfuKQ8bd:bm980q1) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_
https://docs.python.org/2/library/stdtypes.html#str.format

> See Format String Syntax for a description of the various formatting options that can be specified in format strings.
> 
> This method of string formatting is the new standard in Python 3, and should be preferred to the % formatting described in String Formatting Operations in new code.

Nonetheless, feel free to keep it. This is too minor. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by stonemary** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[check_style.py, line 24 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQFL6zGCOKAMeVn3WTl:-KQKJfBcuTqIy2INlNHZ:b32w0x) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/980c29c055aad9bcc5733e48a9df6afcfb51d72c/check_style.py#L24)):_
<details><summary>

<i>Previously, stonemary (小石头) wrote…</i></summary>



> https://docs.python.org/2/library/stdtypes.html#str.format
> 
> > See Format String Syntax for a description of the various formatting options that can be specified in format strings.
> > 
> > This method of string formatting is the new standard in Python 3, and should be preferred to the % formatting described in String Formatting Operations in new code.
> 
> Nonetheless, feel free to keep it. This is too minor. 
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Comment by stonemary** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[python_style_checker.py, line 38 [r2]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6#-KQK9fAi9LR9O8-awAVA:-KQKJwDyhwQegbGjo20i:bo51msy) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/8c7f94669035f6d378e0d4929b1aa96aab3e5827/python_style_checker.py#L38)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> I haven't seen a case where score_found is None so I'll leave it like this for now. Will patch it if it problems arise.
> </details>
> Just make sure Py3 builds then =)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/6)_

**Pull request merged**
