### PR TITLE
bitcount divide and conquer

### PR DESCRIPTION
**Pull request by JesseZhuang**
This change is [Reviewable](https://reviewable.io/reviews/codersinseattle/interviewproblems/10)

### CODE REVIEW

**Comment by yukuairoy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[Problems/src/Bit/Bits.java, line 21 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQHPdPIa0erLnH6vhTX:-KQHPdPJkI3mAwWZMZXh:bbwedjx) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L21)):_

> ``` Java
>   }
> 
>   /** 5 constant operations */
> ```

Please add docstring for what the Bits class and the bitCount() method.

---

_[Problems/src/Bit/Bits.java, line 38 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQHPh4bNLK8J0SNdB3V:-KQHPh4bNLK8J0SNdB3W:buczfko) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L38)):_

> ``` Java
>   }
> 
>   public static void main(String[] args) {
> ```

I suggest moving these to a separate unit test class.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10)_

**Comment by stonemary** [comment]
python这边的unittest runner style checker搞定了。java这边是不是也可以弄个？Jesse愿不愿意弄一个看看。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-:-KQHQan759s5mF0ZQkD1:b6ndvi6)_

**Comment by JesseZhuang** [comment]
@yukuairoy I don't think putting docstring in a java source file would be a good idea. The other two requests will have to go on a waiting list for now.

**Comment by stonemary** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10)_

**Comment by yukuairoy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[Problems/src/Bit/Bits.java, line 23 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQKAAOsAZGoG6jiPmZ0:-KQKAAOsAZGoG6jiPmZ1:b-68insf) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L23)):_

> ``` Java
>   /** 5 constant operations */
>   public static int bitCount(int i) {
>       // HD, Figure 5-2
> ```

This line doesn't make sense, please remove.

---

_[Problems/src/Bit/Bits.java, line 25 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQOk_xyjVDlWpfqmgMb:-KQOk_xyjVDlWpfqmgMc:b-lqgmmy) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L25)):_

> ``` Java
>       // HD, Figure 5-2
>       // put count of each 2 bits into those 2 bits
>       i = i - ((i >>> 1) & 0x55555555); // 01
> ```

Please use m1, m2, etc in place of 0x33333333, 0x0f0f0f0f, etc.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10)_

**Comment by yukuairoy** [comment]
@JesseZhuang I understand that the snippet comes from Java source code, but useful code is supposed to be easily understandable so it can be maintained by others and even yourself, several months later so I still think it's good practice to include at least some basic documentations.

**Comment by JesseZhuang** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[Problems/src/Bit/Bits.java, line 21 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQHPdPIa0erLnH6vhTX:-KQd44NnLyNKQYmFcynd:b-9ssfbe) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L21)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> Please add docstring for what the Bits class and the bitCount() method.
> </details>
> no docstring in java, javadoc added

---

_[Problems/src/Bit/Bits.java, line 23 [r1]](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10#-KQKAAOsAZGoG6jiPmZ0:-KQd4M7OPhM-yMZP5-9d:bikh4jm) ([raw file](https://github.com/codersinseattle/interviewproblems/blob/6472b8c6a0a12b885b3d06a26411246e734becf0/Problems/src/Bit/Bits.java#L23)):_
<details><summary>

<i>Previously, yukuairoy (Kuai Yu) wrote…</i></summary>



> This line doesn't make sense, please remove.
> </details>
> it should be a book, we should leave it there in case anyone can find it

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/codersinseattle/interviewproblems/10)_

**Pull request merged**
